### ISSUE TITLE
Pogledaj ovo

### ISSUE THREAD

**Issue by milesrb92** [plazar23/Slagalica-RecOd12Slova#2]
http://www.dragas.biz/bbc-poslovna-pravila/

**Comment by plazar23** [comment]
To je to. Svidja mi se.
I dopunio bih po koju stavku:

2. Ne obecavaj lako ali ako obecas odrzi rec. I obecanja mozes da posmatras
kao "robu" ako ne vodis racuna i krenes u masovnu proizvodnju ne znaci da
ce vrednost tvoje celokupne robe rasti. Ovakav pristu se koristi u trgovini
umetnickim delima. Umetnici koji prodaju svoja dela za milionske vrednosti
naprave samo 2-3 godisnje. Scarcity tactics.

3. Ovo je jako situaciono. Mislim ne bi valjda govorio sve sto znas pred
svakim. Informacija je druga najvrednija valuta odmah iza vremena.

6.Trudim se da slušam pažljivo ali imam ružnu naviku da prekidam i upadam u
reč mada samo sa onim osobama s kojima sam blizak. To činim iz dva razloga
[1.] zbog staha da se tema promeni pre nego što dobijem reč. Ponekad zvučim
kao da mucam dok činim ovo (Čak sam razmišljao da nosim nekakvu lopticu sa
sobom kako bih izbegao ovakve razgovore. Ko ima lopticu ima reč). Zato samo
kažem kad dobijem misao.
[2.] Kad neko priča osnovu teme i previše detaljno to objašnjava. Želim da
stavim do znanja da sam upoznat sa time i da predje na stvar, da ne gubimo
vreme.

7.Zlatno pravilo.

11. i delaj!!!
